import json, os

BASE = r"c:\Users\chris\OneDrive\Coding Projekte\nibepi\ui\lang"

TRANSLATIONS = {
  "de": {
    "stat.alarmHistory": "Alarmverlauf",
    "stat.alarmStart": "Beginn",
    "stat.alarmEnd": "Ende",
    "stat.alarmActive": "Aktiv",
    "stat.alarmNoHistory": "Keine Alarme aufgezeichnet.",
    "set.backupTitle": "Sicherung & Wiederherstellung",
    "set.backupExport": "Konfiguration exportieren",
    "set.backupImport": "Konfiguration importieren",
    "toast.import": "Konfiguration importiert.",
    "set.mqttTls": "TLS aktivieren (Port 8883)",
    "set.mqttCaFile": "CA-Zertifikatspfad (optional)",
    "reg.write": "Register schreiben",
    "toast.regSet": "Register {0} aktualisiert.",
    "set.authTitle": "Authentifizierung",
    "set.authDesc": "UI mit HTTP Basic Auth schuetzen. Benutzername und Passwort eingeben, dann aktivieren.",
    "set.authEnable": "Authentifizierung aktivieren",
    "set.authUser": "Benutzername",
    "set.authPass": "Passwort",
    "toast.auth": "Authentifizierungseinstellungen gespeichert.",
  },
  "fr": {
    "stat.alarmHistory": "Historique des alarmes",
    "stat.alarmStart": "Debut",
    "stat.alarmEnd": "Fin",
    "stat.alarmActive": "Active",
    "stat.alarmNoHistory": "Aucune alarme enregistree.",
    "set.backupTitle": "Sauvegarde & Restauration",
    "set.backupExport": "Exporter la config",
    "set.backupImport": "Importer la config",
    "toast.import": "Config importee.",
    "set.mqttTls": "Activer TLS (port 8883)",
    "set.mqttCaFile": "Chemin certificat CA (optionnel)",
    "reg.write": "Ecrire registre",
    "toast.regSet": "Registre {0} mis a jour.",
    "set.authTitle": "Authentification",
    "set.authDesc": "Proteger l'interface avec HTTP Basic Auth. Saisir l'identifiant et le mot de passe, puis activer.",
    "set.authEnable": "Activer l'authentification",
    "set.authUser": "Identifiant",
    "set.authPass": "Mot de passe",
    "toast.auth": "Parametres d'authentification sauvegardes.",
  },
  "es": {
    "stat.alarmHistory": "Historial de alarmas",
    "stat.alarmStart": "Inicio",
    "stat.alarmEnd": "Fin",
    "stat.alarmActive": "Activo",
    "stat.alarmNoHistory": "No se han registrado alarmas.",
    "set.backupTitle": "Copia de seguridad y restauracion",
    "set.backupExport": "Exportar config",
    "set.backupImport": "Importar config",
    "toast.import": "Config importada.",
    "set.mqttTls": "Activar TLS (puerto 8883)",
    "set.mqttCaFile": "Ruta certificado CA (opcional)",
    "reg.write": "Escribir registro",
    "toast.regSet": "Registro {0} actualizado.",
    "set.authTitle": "Autenticacion",
    "set.authDesc": "Proteger la interfaz con HTTP Basic Auth. Introducir usuario y contrasena, luego activar.",
    "set.authEnable": "Activar autenticacion",
    "set.authUser": "Usuario",
    "set.authPass": "Contrasena",
    "toast.auth": "Configuracion de autenticacion guardada.",
  },
  "it": {
    "stat.alarmHistory": "Cronologia allarmi",
    "stat.alarmStart": "Inizio",
    "stat.alarmEnd": "Fine",
    "stat.alarmActive": "Attivo",
    "stat.alarmNoHistory": "Nessun allarme registrato.",
    "set.backupTitle": "Backup e ripristino",
    "set.backupExport": "Esporta config",
    "set.backupImport": "Importa config",
    "toast.import": "Config importata.",
    "set.mqttTls": "Abilita TLS (porta 8883)",
    "set.mqttCaFile": "Percorso certificato CA (opzionale)",
    "reg.write": "Scrivi registro",
    "toast.regSet": "Registro {0} aggiornato.",
    "set.authTitle": "Autenticazione",
    "set.authDesc": "Proteggere l'interfaccia con HTTP Basic Auth. Inserire utente e password, poi abilitare.",
    "set.authEnable": "Abilita autenticazione",
    "set.authUser": "Nome utente",
    "set.authPass": "Password",
    "toast.auth": "Impostazioni autenticazione salvate.",
  },
  "nl": {
    "stat.alarmHistory": "Alarmgeschiedenis",
    "stat.alarmStart": "Gestart",
    "stat.alarmEnd": "Beeindigd",
    "stat.alarmActive": "Actief",
    "stat.alarmNoHistory": "Geen alarmen geregistreerd.",
    "set.backupTitle": "Back-up en herstel",
    "set.backupExport": "Config exporteren",
    "set.backupImport": "Config importeren",
    "toast.import": "Config geimporteerd.",
    "set.mqttTls": "TLS inschakelen (poort 8883)",
    "set.mqttCaFile": "CA-certificaatpad (optioneel)",
    "reg.write": "Register schrijven",
    "toast.regSet": "Register {0} bijgewerkt.",
    "set.authTitle": "Authenticatie",
    "set.authDesc": "De interface beveiligen met HTTP Basic Auth. Gebruikersnaam en wachtwoord invoeren, dan inschakelen.",
    "set.authEnable": "Authenticatie inschakelen",
    "set.authUser": "Gebruikersnaam",
    "set.authPass": "Wachtwoord",
    "toast.auth": "Authenticatie-instellingen opgeslagen.",
  },
  "pl": {
    "stat.alarmHistory": "Historia alarmow",
    "stat.alarmStart": "Poczatek",
    "stat.alarmEnd": "Koniec",
    "stat.alarmActive": "Aktywny",
    "stat.alarmNoHistory": "Brak zarejestrowanych alarmow.",
    "set.backupTitle": "Kopia zapasowa i przywracanie",
    "set.backupExport": "Eksportuj konfiguracje",
    "set.backupImport": "Importuj konfiguracje",
    "toast.import": "Konfiguracja zaimportowana.",
    "set.mqttTls": "Wlacz TLS (port 8883)",
    "set.mqttCaFile": "Sciezka certyfikatu CA (opcjonalnie)",
    "reg.write": "Zapisz rejestr",
    "toast.regSet": "Rejestr {0} zaktualizowany.",
    "set.authTitle": "Uwierzytelnianie",
    "set.authDesc": "Chronp interfejs przy uzyciu HTTP Basic Auth. Wprowadz nazwe uzytkownika i haslo, a nastepnie wlacz.",
    "set.authEnable": "Wlacz uwierzytelnianie",
    "set.authUser": "Nazwa uzytkownika",
    "set.authPass": "Haslo",
    "toast.auth": "Ustawienia uwierzytelniania zapisane.",
  },
  "ro": {
    "stat.alarmHistory": "Istoricul alarmelor",
    "stat.alarmStart": "Inceput",
    "stat.alarmEnd": "Sfarsit",
    "stat.alarmActive": "Activ",
    "stat.alarmNoHistory": "Nicio alarma inregistrata.",
    "set.backupTitle": "Backup si restaurare",
    "set.backupExport": "Exporta config",
    "set.backupImport": "Importa config",
    "toast.import": "Config importat.",
    "set.mqttTls": "Activeaza TLS (port 8883)",
    "set.mqttCaFile": "Cale certificat CA (optional)",
    "reg.write": "Scrie registru",
    "toast.regSet": "Registrul {0} actualizat.",
    "set.authTitle": "Autentificare",
    "set.authDesc": "Protejati interfata cu HTTP Basic Auth. Introduceti utilizatorul si parola, apoi activati.",
    "set.authEnable": "Activeaza autentificarea",
    "set.authUser": "Utilizator",
    "set.authPass": "Parola",
    "toast.auth": "Setarile de autentificare salvate.",
  },
  "hu": {
    "stat.alarmHistory": "Riasztas-tortenelem",
    "stat.alarmStart": "Kezdet",
    "stat.alarmEnd": "Veg",
    "stat.alarmActive": "Aktiv",
    "stat.alarmNoHistory": "Nem rogzitettek riasztast.",
    "set.backupTitle": "Biztonsagi mentes es visszaallitas",
    "set.backupExport": "Konfiguracio exportalasa",
    "set.backupImport": "Konfiguracio importalasa",
    "toast.import": "Konfiguracio importalva.",
    "set.mqttTls": "TLS engedelyezese (8883-as port)",
    "set.mqttCaFile": "CA tanusitvany eleresi utja (opcionalis)",
    "reg.write": "Regiszter irasa",
    "toast.regSet": "{0} regiszter frissitve.",
    "set.authTitle": "Hitelesites",
    "set.authDesc": "Vedje az UI-t HTTP Basic Auth segitsegevel. Adja meg a felhasznalonevet es a jelszot, majd engedelyezze.",
    "set.authEnable": "Hitelesites engedelyezese",
    "set.authUser": "Felhasznalonev",
    "set.authPass": "Jelszo",
    "toast.auth": "Hitelesitesi beallitasok mentve.",
  },
  "el": {
    "stat.alarmHistory": "Ιστορικό συναγερμών",
    "stat.alarmStart": "Έναρξη",
    "stat.alarmEnd": "Λήξη",
    "stat.alarmActive": "Ενεργός",
    "stat.alarmNoHistory": "Δεν έχουν καταγραφεί συναγερμοί.",
    "set.backupTitle": "Αντίγραφο & Επαναφορά",
    "set.backupExport": "Εξαγωγή ρυθμίσεων",
    "set.backupImport": "Εισαγωγή ρυθμίσεων",
    "toast.import": "Ρυθμίσεις εισήχθησαν.",
    "set.mqttTls": "Ενεργοποίηση TLS (θύρα 8883)",
    "set.mqttCaFile": "Διαδρομή πιστοποιητικού CA (προαιρετικό)",
    "reg.write": "Εγγραφή μητρώου",
    "toast.regSet": "Μητρώο {0} ενημερώθηκε.",
    "set.authTitle": "Αυθεντικοποίηση",
    "set.authDesc": "Προστατέψτε το UI με HTTP Basic Auth. Εισαγάγετε όνομα χρήστη και κωδικό, έπειτα ενεργοποιήστε.",
    "set.authEnable": "Ενεργοποίηση αυθεντικοποίησης",
    "set.authUser": "Όνομα χρήστη",
    "set.authPass": "Κωδικός",
    "toast.auth": "Ρυθμίσεις αυθεντικοποίησης αποθηκεύτηκαν.",
  },
  "sv": {
    "stat.alarmHistory": "Larmhistorik",
    "stat.alarmStart": "Startade",
    "stat.alarmEnd": "Avslutade",
    "stat.alarmActive": "Aktiv",
    "stat.alarmNoHistory": "Inga larm registrerade.",
    "set.backupTitle": "Saekerhetskopiering & Aaterstaellning",
    "set.backupExport": "Exportera konfiguration",
    "set.backupImport": "Importera konfiguration",
    "toast.import": "Konfiguration importerad.",
    "set.mqttTls": "Aktivera TLS (port 8883)",
    "set.mqttCaFile": "Soekvaeg till CA-certifikat (valfritt)",
    "reg.write": "Skriv register",
    "toast.regSet": "Register {0} uppdaterat.",
    "set.authTitle": "Autentisering",
    "set.authDesc": "Skydda UI med HTTP Basic Auth. Ange anvaendarnamn och loesenord, aktivera sedan.",
    "set.authEnable": "Aktivera autentisering",
    "set.authUser": "Anvaendarnamn",
    "set.authPass": "Loesenord",
    "toast.auth": "Autentiseringsinstaellningar sparade.",
  },
  "no": {
    "stat.alarmHistory": "Alarmhistorikk",
    "stat.alarmStart": "Startet",
    "stat.alarmEnd": "Avsluttet",
    "stat.alarmActive": "Aktiv",
    "stat.alarmNoHistory": "Ingen alarmer registrert.",
    "set.backupTitle": "Sikkerhetskopiering & Gjenoppretting",
    "set.backupExport": "Eksporter konfigurasjon",
    "set.backupImport": "Importer konfigurasjon",
    "toast.import": "Konfigurasjon importert.",
    "set.mqttTls": "Aktiver TLS (port 8883)",
    "set.mqttCaFile": "Sti til CA-sertifikat (valgfritt)",
    "reg.write": "Skriv register",
    "toast.regSet": "Register {0} oppdatert.",
    "set.authTitle": "Autentisering",
    "set.authDesc": "Beskytt UI med HTTP Basic Auth. Angi brukernavn og passord, aktiver deretter.",
    "set.authEnable": "Aktiver autentisering",
    "set.authUser": "Brukernavn",
    "set.authPass": "Passord",
    "toast.auth": "Autentiseringsinnstillinger lagret.",
  },
  "da": {
    "stat.alarmHistory": "Alarmhistorik",
    "stat.alarmStart": "Startet",
    "stat.alarmEnd": "Afsluttet",
    "stat.alarmActive": "Aktiv",
    "stat.alarmNoHistory": "Ingen alarmer registreret.",
    "set.backupTitle": "Sikkerhedskopi & Gendannelse",
    "set.backupExport": "Eksporter konfiguration",
    "set.backupImport": "Importer konfiguration",
    "toast.import": "Konfiguration importeret.",
    "set.mqttTls": "Aktiver TLS (port 8883)",
    "set.mqttCaFile": "Sti til CA-certifikat (valgfrit)",
    "reg.write": "Skriv register",
    "toast.regSet": "Register {0} opdateret.",
    "set.authTitle": "Godkendelse",
    "set.authDesc": "Beskyt UI med HTTP Basic Auth. Indtast brugernavn og adgangskode, aktiver derefter.",
    "set.authEnable": "Aktiver godkendelse",
    "set.authUser": "Brugernavn",
    "set.authPass": "Adgangskode",
    "toast.auth": "Godkendelsesindstillinger gemt.",
  },
  "fi": {
    "stat.alarmHistory": "Hälytyshistoria",
    "stat.alarmStart": "Alkanut",
    "stat.alarmEnd": "Päättynyt",
    "stat.alarmActive": "Aktiivinen",
    "stat.alarmNoHistory": "Ei kirjattuja hälytyksiä.",
    "set.backupTitle": "Varmuuskopiointi & Palautus",
    "set.backupExport": "Vie kokoonpano",
    "set.backupImport": "Tuo kokoonpano",
    "toast.import": "Kokoonpano tuotu.",
    "set.mqttTls": "Ota TLS käyttöön (portti 8883)",
    "set.mqttCaFile": "CA-varmenteen polku (valinnainen)",
    "reg.write": "Kirjoita rekisteri",
    "toast.regSet": "Rekisteri {0} päivitetty.",
    "set.authTitle": "Todennus",
    "set.authDesc": "Suojaa käyttöliittymä HTTP Basic Auth -todennuksella. Syötä käyttäjänimi ja salasana, sitten ota käyttöön.",
    "set.authEnable": "Ota todennus käyttöön",
    "set.authUser": "Käyttäjänimi",
    "set.authPass": "Salasana",
    "toast.auth": "Todennusasetukset tallennettu.",
  },
  "pt": {
    "stat.alarmHistory": "Histórico de alarmes",
    "stat.alarmStart": "Início",
    "stat.alarmEnd": "Fim",
    "stat.alarmActive": "Ativo",
    "stat.alarmNoHistory": "Nenhum alarme registado.",
    "set.backupTitle": "Cópia de segurança & Restauro",
    "set.backupExport": "Exportar configuração",
    "set.backupImport": "Importar configuração",
    "toast.import": "Configuração importada.",
    "set.mqttTls": "Ativar TLS (porta 8883)",
    "set.mqttCaFile": "Caminho do certificado CA (opcional)",
    "reg.write": "Escrever registo",
    "toast.regSet": "Registo {0} atualizado.",
    "set.authTitle": "Autenticação",
    "set.authDesc": "Proteger a interface com HTTP Basic Auth. Introduzir utilizador e palavra-passe, depois ativar.",
    "set.authEnable": "Ativar autenticação",
    "set.authUser": "Utilizador",
    "set.authPass": "Palavra-passe",
    "toast.auth": "Definições de autenticação guardadas.",
  },
  "cs": {
    "stat.alarmHistory": "Historie alarmů",
    "stat.alarmStart": "Začátek",
    "stat.alarmEnd": "Konec",
    "stat.alarmActive": "Aktivní",
    "stat.alarmNoHistory": "Žádné alarmy nebyly zaznamenány.",
    "set.backupTitle": "Záloha & Obnovení",
    "set.backupExport": "Exportovat konfiguraci",
    "set.backupImport": "Importovat konfiguraci",
    "toast.import": "Konfigurace importována.",
    "set.mqttTls": "Povolit TLS (port 8883)",
    "set.mqttCaFile": "Cesta k CA certifikátu (volitelné)",
    "reg.write": "Zapsat registr",
    "toast.regSet": "Registr {0} aktualizován.",
    "set.authTitle": "Ověřování",
    "set.authDesc": "Chraňte UI pomocí HTTP Basic Auth. Zadejte uživatelské jméno a heslo, poté aktivujte.",
    "set.authEnable": "Povolit ověřování",
    "set.authUser": "Uživatelské jméno",
    "set.authPass": "Heslo",
    "toast.auth": "Nastavení ověřování uloženo.",
  },
  "sk": {
    "stat.alarmHistory": "História alarmov",
    "stat.alarmStart": "Začiatok",
    "stat.alarmEnd": "Koniec",
    "stat.alarmActive": "Aktívny",
    "stat.alarmNoHistory": "Žiadne alarmy neboli zaznamenané.",
    "set.backupTitle": "Záloha & Obnovenie",
    "set.backupExport": "Exportovať konfiguráciu",
    "set.backupImport": "Importovať konfiguráciu",
    "toast.import": "Konfigurácia importovaná.",
    "set.mqttTls": "Povoliť TLS (port 8883)",
    "set.mqttCaFile": "Cesta k CA certifikátu (voliteľné)",
    "reg.write": "Zapísať register",
    "toast.regSet": "Register {0} aktualizovaný.",
    "set.authTitle": "Overenie",
    "set.authDesc": "Chráňte UI pomocou HTTP Basic Auth. Zadajte používateľské meno a heslo, potom aktivujte.",
    "set.authEnable": "Povoliť overenie",
    "set.authUser": "Používateľské meno",
    "set.authPass": "Heslo",
    "toast.auth": "Nastavenia overenia uložené.",
  },
  "sl": {
    "stat.alarmHistory": "Zgodovina alarmov",
    "stat.alarmStart": "Začetek",
    "stat.alarmEnd": "Konec",
    "stat.alarmActive": "Aktiven",
    "stat.alarmNoHistory": "Ni zabeleženih alarmov.",
    "set.backupTitle": "Varnostna kopija & Obnovitev",
    "set.backupExport": "Izvozi nastavitve",
    "set.backupImport": "Uvozi nastavitve",
    "toast.import": "Nastavitve uvožene.",
    "set.mqttTls": "Omogoči TLS (vrata 8883)",
    "set.mqttCaFile": "Pot do CA certifikata (neobvezno)",
    "reg.write": "Zapiši register",
    "toast.regSet": "Register {0} posodobljen.",
    "set.authTitle": "Overjanje",
    "set.authDesc": "Zaščitite UI z HTTP Basic Auth. Vnesite uporabniško ime in geslo, nato omogočite.",
    "set.authEnable": "Omogoči overjanje",
    "set.authUser": "Uporabniško ime",
    "set.authPass": "Geslo",
    "toast.auth": "Nastavitve overjanja shranjene.",
  },
  "hr": {
    "stat.alarmHistory": "Povijest alarma",
    "stat.alarmStart": "Početak",
    "stat.alarmEnd": "Kraj",
    "stat.alarmActive": "Aktivan",
    "stat.alarmNoHistory": "Nisu zabilježeni alarmi.",
    "set.backupTitle": "Sigurnosna kopija & Obnova",
    "set.backupExport": "Izvezi postavke",
    "set.backupImport": "Uvezi postavke",
    "toast.import": "Postavke uvezene.",
    "set.mqttTls": "Omogući TLS (priključak 8883)",
    "set.mqttCaFile": "Put do CA certifikata (neobavezno)",
    "reg.write": "Upiši registar",
    "toast.regSet": "Registar {0} ažuriran.",
    "set.authTitle": "Autentifikacija",
    "set.authDesc": "Zaštitite sučelje pomoću HTTP Basic Auth. Unesite korisničko ime i lozinku, zatim omogućite.",
    "set.authEnable": "Omogući autentifikaciju",
    "set.authUser": "Korisničko ime",
    "set.authPass": "Lozinka",
    "toast.auth": "Postavke autentifikacije spremljene.",
  },
}

for lang, new_keys in TRANSLATIONS.items():
    fpath = os.path.join(BASE, f"{lang}.json")
    with open(fpath, encoding='utf-8') as f:
        data = json.load(f)
    data.update(new_keys)
    with open(fpath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write('\n')
    print(f"Updated {lang}.json ({len(data)} keys)")

print("Done.")
